services:
  - type: web
    name: abyss-irc-server
    runtime: node
    plan: free
    rootDir: IRC/server
    buildCommand: npm install && npm run build
    startCommand: npm run start
    autoDeploy: true
    healthCheckPath: /healthz
    envVars:
      - key: IRC_SERVER_HOST
        value: 0.0.0.0
      - key: IRC_ALLOWED_ORIGINS
        value: https://abyss-irc-client.onrender.com

  - type: web
    name: abyss-irc-client
    runtime: static
    rootDir: IRC/client
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_IRC_SERVER_URL
        fromService:
          type: web
          name: abyss-irc-server
          envVarKey: RENDER_EXTERNAL_URL
